import { z } from 'zod';

// The Blueprint schema generated by the Profiler
export const BlueprintSchema = z.object({
  title: z.string().describe("The title of the chapter"),
  targetWordCount: z.number().describe("The target word count for this chapter, e.g. 1500"),
  difficultyLevel: z.number().min(1).max(10).describe("Difficulty level from 1-10"),
  requiredTopics: z.array(z.string()).describe("List of exact concepts that MUST be covered"),
  recommendedTone: z.string().describe("E.g., 'academic', 'conversational', 'step-by-step tutorial'"),
});

export type Blueprint = z.infer<typeof BlueprintSchema>;

// The Content Blocks schema generated by the Content Drafter
export const ContentBlockSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('text'),
    markdown: z.string().describe("Standard markdown text. Do NOT include LaTeX $$ or Mermaid here."),
  }),
  z.object({
    type: z.literal('formula'),
    latex: z.string().describe("Pure LaTeX code WITHOUT wrapping $$ or \\[ signs. E.g. 'E = mc^2'"),
    isBlock: z.boolean().describe("True if it should be displayed on its own line (block math), false for inline."),
  }),
  z.object({
    type: z.literal('diagram'),
    mermaidCode: z.string().describe("Pure Mermaid code WITHOUT wrapping ```mermaid or markdown backticks."),
    caption: z.string().optional().describe("A descriptive caption for the diagram"),
  })
]);

export const ChapterContentSchema = z.object({
  blocks: z.array(ContentBlockSchema).describe("An array of content blocks that make up the entire chapter."),
});

export type ContentBlock = z.infer<typeof ContentBlockSchema>;
export type ChapterContent = z.infer<typeof ChapterContentSchema>;
